# Generated by Django 5.2.10 on 2026-03-29 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0002_cart_added_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
