# Generated by Django 5.2.11 on 2026-02-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restframework', '0002_remove_student_id_alter_student_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='Firstname',
        ),
        migrations.AddField(
            model_name='student',
            name='Lastname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
