# Generated by Django 5.2.10 on 2026-02-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restframework', '0003_rename_name_student_firstname_student_lastname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('units', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='YearLevel',
            fields=[
                ('year_level_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Firstname',
            new_name='Fullname',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='relationship_status',
            new_name='year_level',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Lastname',
        ),
    ]
