# Generated by Django 5.2.10 on 2026-02-23 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restframework', '0004_course_yearlevel_rename_firstname_student_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restframework.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restframework.yearlevel'),
        ),
    ]
